# Site settings
title: Nervous Concept
description: Nervous Concept blog
email: contact@NervousConcept.com
baseurl: /
url: "https://nervousconcept.github.io/" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
feedburner_username: NervousConcept

#twitter
twitter_username: NervousConcept
github_username:  NervousConcept

#linkedin
linkedin_username: NervousConcept

#google analytics
google_analytics_id : UA-11111111-1
#gplus
gplus_username: 111111111111111111111

#fb_username
fb_username: NervousConcept

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: NervousConcept
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  NervousConcept:
    display_name: Nervous Concept
    email: contact@NervousConcept.com
    fb: NervousConcept
    linkedin: NervousConcept
    twitter: NervousConcept
    github: NervousConcept
